"""add project search indexes

Revision ID: 11bca64bbcf9
Revises: 0db52e9a12fa
Create Date: 2026-04-08 12:13:10.021273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11bca64bbcf9"
down_revision: Union[str, Sequence[str], None] = "0db52e9a12fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "ix_projects_published_active_top_order",
        "projects",
        [
            sa.literal_column("vote_count DESC"),
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        postgresql_where=sa.text("is_published = true AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_projects_short_description_lower_trgm",
        "projects",
        [sa.literal_column("lower(short_description) gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_projects_title_lower_trgm",
        "projects",
        [sa.literal_column("lower(title) gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_projects_title_lower_trgm", table_name="projects", postgresql_using="gin"
    )
    op.drop_index(
        "ix_projects_short_description_lower_trgm",
        table_name="projects",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_projects_published_active_top_order",
        table_name="projects",
        postgresql_where=sa.text("is_published = true AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
