"""split project descriptions and tighten title length

Revision ID: 267ed6415e27
Revises: bc2a826321e6
Create Date: 2026-03-11 16:58:15.909451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "267ed6415e27"
down_revision: Union[str, Sequence[str], None] = "bc2a826321e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("short_description", sa.String(length=280), nullable=False),
    )
    op.add_column("projects", sa.Column("long_description", sa.Text(), nullable=True))
    op.alter_column(
        "projects",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=120),
        existing_nullable=False,
    )
    op.drop_column("projects", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "projects",
        "title",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("projects", "long_description")
    op.drop_column("projects", "short_description")
    # ### end Alembic commands ###
