"""add project timeline date fields

Revision ID: 587cb6550d2f
Revises: d529c433d293
Create Date: 2026-03-27 13:09:12.174489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "587cb6550d2f"
down_revision: Union[str, Sequence[str], None] = "d529c433d293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("timeline_start_date", sa.Date(), nullable=True)
    )
    op.add_column("projects", sa.Column("timeline_end_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "timeline_end_date")
    op.drop_column("projects", "timeline_start_date")
    # ### end Alembic commands ###
