"""add taxonomy tables and project term joins

Revision ID: 5eaf589e841f
Revises: 587cb6550d2f
Create Date: 2026-04-03 15:05:34.646449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5eaf589e841f"
down_revision: Union[str, Sequence[str], None] = "587cb6550d2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("normalized_name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_normalized_name"),
        "categories",
        ["normalized_name"],
        unique=True,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("normalized_name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tags_normalized_name"), "tags", ["normalized_name"], unique=True
    )
    op.create_table(
        "tech_stacks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("normalized_name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tech_stacks_normalized_name"),
        "tech_stacks",
        ["normalized_name"],
        unique=True,
    )
    op.create_table(
        "project_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "category_id",
            name="uq_project_categories_project_id_category_id",
        ),
        sa.UniqueConstraint(
            "project_id", "position", name="uq_project_categories_project_id_position"
        ),
    )
    op.create_index(
        op.f("ix_project_categories_category_id"),
        "project_categories",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_categories_category_id_project_id",
        "project_categories",
        ["category_id", "project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_categories_project_id"),
        "project_categories",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "position", name="uq_project_tags_project_id_position"
        ),
        sa.UniqueConstraint(
            "project_id", "tag_id", name="uq_project_tags_project_id_tag_id"
        ),
    )
    op.create_index(
        op.f("ix_project_tags_project_id"), "project_tags", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_tags_tag_id"), "project_tags", ["tag_id"], unique=False
    )
    op.create_index(
        "ix_project_tags_tag_id_project_id",
        "project_tags",
        ["tag_id", "project_id"],
        unique=False,
    )
    op.create_table(
        "project_tech_stacks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("tech_stack_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tech_stack_id"],
            ["tech_stacks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "position", name="uq_project_tech_stacks_project_id_position"
        ),
        sa.UniqueConstraint(
            "project_id",
            "tech_stack_id",
            name="uq_project_tech_stacks_project_id_tech_stack_id",
        ),
    )
    op.create_index(
        op.f("ix_project_tech_stacks_project_id"),
        "project_tech_stacks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_tech_stacks_tech_stack_id"),
        "project_tech_stacks",
        ["tech_stack_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_tech_stacks_tech_stack_id_project_id",
        "project_tech_stacks",
        ["tech_stack_id", "project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_tech_stacks_tech_stack_id_project_id",
        table_name="project_tech_stacks",
    )
    op.drop_index(
        op.f("ix_project_tech_stacks_tech_stack_id"), table_name="project_tech_stacks"
    )
    op.drop_index(
        op.f("ix_project_tech_stacks_project_id"), table_name="project_tech_stacks"
    )
    op.drop_table("project_tech_stacks")
    op.drop_index("ix_project_tags_tag_id_project_id", table_name="project_tags")
    op.drop_index(op.f("ix_project_tags_tag_id"), table_name="project_tags")
    op.drop_index(op.f("ix_project_tags_project_id"), table_name="project_tags")
    op.drop_table("project_tags")
    op.drop_index(
        op.f("ix_project_categories_project_id"), table_name="project_categories"
    )
    op.drop_index(
        "ix_project_categories_category_id_project_id", table_name="project_categories"
    )
    op.drop_index(
        op.f("ix_project_categories_category_id"), table_name="project_categories"
    )
    op.drop_table("project_categories")
    op.drop_index(op.f("ix_tech_stacks_normalized_name"), table_name="tech_stacks")
    op.drop_table("tech_stacks")
    op.drop_index(op.f("ix_tags_normalized_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_categories_normalized_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
