"""drop redundant taxonomy join indexes

Revision ID: 867e13020b84
Revises: 5eaf589e841f
Create Date: 2026-04-03 15:50:32.623527

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "867e13020b84"
down_revision: Union[str, Sequence[str], None] = "5eaf589e841f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_categories_category_id"), table_name="project_categories"
    )
    op.drop_index(
        op.f("ix_project_categories_project_id"), table_name="project_categories"
    )
    op.drop_index(op.f("ix_project_tags_project_id"), table_name="project_tags")
    op.drop_index(op.f("ix_project_tags_tag_id"), table_name="project_tags")
    op.drop_index(
        op.f("ix_project_tech_stacks_project_id"), table_name="project_tech_stacks"
    )
    op.drop_index(
        op.f("ix_project_tech_stacks_tech_stack_id"), table_name="project_tech_stacks"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_project_tech_stacks_tech_stack_id"),
        "project_tech_stacks",
        ["tech_stack_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_tech_stacks_project_id"),
        "project_tech_stacks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_tags_tag_id"), "project_tags", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_tags_project_id"), "project_tags", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_categories_project_id"),
        "project_categories",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_categories_category_id"),
        "project_categories",
        ["category_id"],
        unique=False,
    )
    # ### end Alembic commands ###
