"""constrain comment moderation state

Revision ID: c522d05b3a2a
Revises: 38d8508979fe
Create Date: 2026-04-12 15:20:19.175489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c522d05b3a2a"
down_revision: Union[str, Sequence[str], None] = "38d8508979fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments",
        "moderation_state",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Enum(
            "visible",
            "hidden",
            name="comment_moderation_state",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'visible'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments",
        "moderation_state",
        existing_type=sa.Enum(
            "visible",
            "hidden",
            name="comment_moderation_state",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        existing_server_default=sa.text("'visible'::character varying"),
    )
    # ### end Alembic commands ###
