"""reduce project title max length to 50

Revision ID: d529c433d293
Revises: 267ed6415e27
Create Date: 2026-03-11 17:11:19.482165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d529c433d293"
down_revision: Union[str, Sequence[str], None] = "267ed6415e27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "title",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "title",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
