"""require project description

Revision ID: fd844bc3715b
Revises: 43660c323ec3
Create Date: 2026-02-25 13:50:20.202949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd844bc3715b"
down_revision: Union[str, Sequence[str], None] = "43660c323ec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "description", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
